### ISSUE TITLE
got error: "RuntimeError: you must first build vocabulary before training the model"

### ISSUE THREAD

**Issue by ANUDAVIS** [jacopotagliabue/retail-personalization-workshop#1]
![1](https://user-images.githubusercontent.com/22854116/143779964-63c1cfa2-897c-4b05-b640-b0aabeb8d02c.png)
![2](https://user-images.githubusercontent.com/22854116/143779969-314e6ef7-31c3-464b-9390-99359481f4d2.png)

**Comment by jacopotagliabue** [comment]
Hi, it looks like the len(train_sessions) is wrong (0), so there is something wrong with the train/test split or the sessions object itself. The error in the function seem to be related to sessions not being there, more than a code error per se.

**Comment by ANUDAVIS** [comment]
error got solved by adding a code line: "sessions=sessions[0]" in below
that is :
# get sessions
sessions = read_sessions_from_training_file(
    training_file=os.path.join(LOCAL_FOLDER, 'browsing_train.csv'),
    K=N_ROWS)
sku_cnt = Counter([item for s in sessions for item in s])
sku_cnt.most_common(3)
print(sessions)
sessions=sessions[0]
