### ISSUE TITLE
got an error : KeyError: "Key 'd5157f8bc52965390fa21ad5842a8502bc3eb8b0930f3f8eafbc503f4012f69c' not present"

### ISSUE THREAD

**Issue by ANUDAVIS** [jacopotagliabue/retail-personalization-workshop#2]
![4](https://user-images.githubusercontent.com/22854116/143826408-3d28c986-9d9f-4370-9122-ba1139ba8a9d.png)
![3](https://user-images.githubusercontent.com/22854116/143826426-0d031f8c-e05e-42b3-8860-3c18caa26f03.png)

**Comment by jacopotagliabue** [comment]
Hi, this is not an error per se: it is a normal issue with ML in e-commerce, the "cold start" (e.g. https://dl.acm.org/doi/10.1145/3383313.3411477) - the item you're looking for is not in the space and it may depend from the type of training slice you prepared as compared to what the code was originally doing. Please make sure to read the relevant literature to get a good grasp on what the code is doing.

**Comment by ANUDAVIS** [comment]
yes I got sir, but the scene is the keyword I am using is inside the set itself and its showing key not found
