### ISSUE TITLE
Using custom dataset

### ISSUE THREAD

**Issue by ANUDAVIS** [jacopotagliabue/retail-personalization-workshop#3]
how we can create browsing_train.csv,  search_train.csv, and sku_to_content.csv from a custom dataset.
I searched in many but couldn't find anything Please help

**Comment by jacopotagliabue** [comment]
Hi thanks for your interest, the dataset is fully described, with example and literature, here: https://github.com/coveooss/SIGIR-ecom-data-challenge. You can use those information to create your own or modify the code to read a different format for SKUs etc.

Hope it helps!
